sudo: required
services:
  - docker

before_install:
  - docker build -t arnab1991/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true arnab1991/docker-react yarn run test -- --coverage
