#import a remote base image
FROM node:alpine as builder
#define a folder in the container to start the application
WORKDIR '/app'
#copy specific file needed to run npm install
#COPY package.json .
#Build image with npm install

RUN npm install yarn

COPY package.json .


RUN yarn install
RUN yarn cache clean

COPY . .

CMD ["yarn","start"]